version: "3.7"
services:

  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
      - /api/node_modules
    container_name: API_TASK
  
  app:
    build: ./app
    ports:
      - 4200:4200
    volumes:
      - ./app:/app
      - /app/node_modules
    container_name: APP_TASK
